### ISSUE TITLE
'Grid' object has no attribute '_nx'

### ISSUE THREAD

**Issue by TimoRoth** [fmaussion/salem#51] opened 2017-01-10 14:31 UTC
After trying to update the Docker image, it fails running its tests with the following error:

```
ERROR: test_invert_and_run (oggm.tests.test_prepro.TestGrindelInvert)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/oggm/tests/test_prepro.py", line 1313, in test_invert_and_run

    gis.glacier_masks(gdir)

  File "/usr/local/lib/python3.5/dist-packages/oggm/utils.py", line 1442, in _entity_task

    out = task_func(gdir, **kwargs)

  File "/usr/local/lib/python3.5/dist-packages/oggm/core/preprocessing/gis.py", line 509, in glacier_masks

    assert nx == gdir.grid.nx

  File "/usr/local/lib/python3.5/dist-packages/salem/gis.py", line 273, in nx

    return self._nx

AttributeError: 'Grid' object has no attribute '_nx'
```

Haven't had time to investigate yet, as I'm still on vacation, will Update here if I find out more.

**Comment by fmaussion** [comment] 2017-01-10 15:45
thanks @TimoRoth 

It looks like an ugly pickle issue, and rather a problem in OGGM. I'll have a look too

Happy holidays!

**Comment by fmaussion** [comment] 2017-01-10 17:17
Yes, I can confirm that the problem is here: https://github.com/OGGM/oggm-sample-data/blob/master/realisation/RGI50-11.01270/glacier_grid.pkl

I'll try to find a solution. 

Pickle serialization is so practical but such a bad idea :(

**Comment by fmaussion** [comment] 2017-01-10 17:21
closing in favor of https://github.com/OGGM/oggm/issues/148 and https://github.com/fmaussion/salem/issues/53

**Closed by fmaussion** 2017-01-10 17:21 UTC
