### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kurkutesa** [fmaussion/salem#95] opened 2018-03-15 01:32 UTC
I got `Segmentation fault (core dumped)` error when i tried `import salem` . Could anyone address this issue ?
Thank You

**Comment by tbridel** [comment] 2018-03-15 06:45
Hello kurkutesa,

Can you please tell us what version of salem you are using right now ? The branch and/or commit hash would probably help trying to track down the issue.
Also, can you provide us with the whole header to your python file ? Do you import other modules before salem ?

Cheers !

**Comment by fmaussion** [comment] 2018-11-13 08:57
Closing this, feel free to re-open if this occurs again

**Closed by fmaussion** 2018-11-13 08:57 UTC

**Comment by catzrin** [comment] 2019-04-10 04:39
Hi, just to note I am also getting the same error `Segmentation fault (core dumped)`

I have version `0.2.4` of salem installed (I also tried installing the latest master, `salem-0.2.4-1-g08dc357` and got the same problem. 

I get the segfault even when importing salem is the only thing I do, ie the only thing in the file is 
`import salem`

Any help with this issue would be appreciated thankyou.

**Comment by fmaussion** [comment] 2019-04-10 08:24
This is *very* unlikely to be related to salem itself, but one of its dependencies. If I had to bet, I would bet on fiona. What happens when you do `import fiona` in a terminal?

I've seen other people having issues with fiona/gdal and conda on their machine, and unfortunately I don't have a solution for this...

**Comment by catzrin** [comment] 2019-04-10 23:31
Thanks for your input; this is what I get:

`
>>>Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
>>>[GCC 7.3.0] :: Anaconda, Inc. on linux
>>>Type "help", "copyright", "credits" or "license" for more information.
>>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/catm/anaconda3/lib/python3.7/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/catm/anaconda3/lib/python3.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: /home/catm/anaconda3/lib/python3.7/site-packages/fiona/../../../libgdal.so.20: undefined symbol: _ZNK6libdap5Error17get_error_messageB5cxx11Ev
`

**Comment by fmaussion** [comment] 2019-04-11 06:56
Yes, this is what I meant - the problem is not in salem but in your installation. So you should try to do a fresh install, or maybe search the anaconda or conda-forge issues for similar errors. Sorry I can't help!
